export const ProjectsList = [
  {
    id: 1,
    images: [
      {
        src: "/images/projects/idu-duplex/cover.png",
        alt: "Front view of Idu Duplex",
        width: 2000,
        height: 2000,
      },
      {
        src: "/images/projects/idu-duplex/1.jpg",
        alt: "Side view of Idu Duplex",
        width: 2000,
        height: 2000,
      },
      {
        src: "/images/projects/idu-duplex/2.jpg",
        alt: "Gazebo of Idu Duplex",
        width: 2000,
        height: 2000,
      },
      {
        src: "/images/projects/idu-duplex/3.jpg",
        alt: "Idu Duplex room 1",
        width: 2000,
        height: 2000,
      },
      {
        src: "/images/projects/idu-duplex/4.jpg",
        alt: "Idu Duplex room 2",
        width: 2000,
        height: 2000,
      },
      {
        src: "/images/projects/idu-duplex/5.jpg",
        alt: "Idu duplex room 3",
        width: 2000,
        height: 2000,
      },
      {
        src: "/images/projects/idu-duplex/6.jpg",
        alt: "Idu Duplex room 4",
        width: 2000,
        height: 2000,
      },
      {
        src: "/images/projects/idu-duplex/7.jpg",
        alt: "Idu Duplex room 5",
        width: 2000,
        height: 2000,
      },
      {
        src: "/images/projects/idu-duplex/8.jpg",
        alt: "Idu Duplex room lobby",
        width: 2000,
        height: 2000,
      },
      {
        src: "/images/projects/idu-duplex/9.jpg",
        alt: "Idu Duplex toilet",
        width: 2000,
        height: 2000,
      },
      {
        src: "/images/projects/idu-duplex/10.jpg",
        alt: "Idu Duplex front render",
        width: 2000,
        height: 2000,
      },
      {
        src: "/images/projects/idu-duplex/11.jpg",
        alt: "Idu Duplex side render",
        width: 2000,
        height: 2000,
      },
      {
        src: "/images/projects/idu-duplex/12.jpg",
        alt: "Idu Duplex isometric render",
        width: 2000,
        height: 2000,
      },
    ],
    title: "Idu Duplex",
    location: "Idu, Abuja",
    period: "2023",
    status: "Finished",
    client: "Nasiru Sabo",
    service: "Full design and project supervision",
  },
  {
    id: 2,
    images: [
      {
        src: "/images/projects/mabushi-apartment/cover.jpg",
        alt: "Mabushi Apartment outside view",
        width: 2000,
        height: 2000,
      },
      {
        src: "/images/projects/mabushi-apartment/1.jpg",
        alt: "Mabushi Apartment front view",
        width: 2000,
        height: 2000,
      },
      {
        src: "/images/projects/mabushi-apartment/2.jpg",
        alt: "Mabushi Apartment living room",
        width: 2000,
        height: 2000,
      },
      {
        src: "/images/projects/mabushi-apartment/3.jpg",
        alt: "Mabushi Apartment room",
        width: 2000,
        height: 2000,
      },
      {
        src: "/images/projects/mabushi-apartment/4.jpg",
        alt: "Mabushi Apartment room",
        width: 2000,
        height: 2000,
      },
      {
        src: "/images/projects/mabushi-apartment/5.jpg",
        alt: "Mabushi Apartment kitchen",
        width: 2000,
        height: 2000,
      },
      {
        src: "/images/projects/mabushi-apartment/6.jpg",
        alt: "Mabushi Apartment toilet",
        width: 2000,
        height: 2000,
      },
      {
        src: "/images/projects/mabushi-apartment/7.jpg",
        alt: "Mabushi Apartment kitchen",
        width: 2000,
        height: 2000,
      },
      {
        src: "/images/projects/mabushi-apartment/8.jpg",
        alt: "Mabushi Apartment kitchen",
        width: 2000,
        height: 2000,
      },
      {
        src: "/images/projects/mabushi-apartment/9.jpg",
        alt: "Mabushi Apartment corridor",
        width: 2000,
        height: 2000,
      },
      {
        src: "/images/projects/mabushi-apartment/10.jpg",
        alt: "Mabushi Apartment toilet",
        width: 2000,
        height: 2000,
      },
      {
        src: "/images/projects/mabushi-apartment/11.jpg",
        alt: "Mabushi Apartment toilet",
        width: 2000,
        height: 2000,
      },
    ],
    title: "Mabushi Apartment",
    location: "Mabushi, Abuja",
    period: "2023",
    status: "Finished",
    client: "Diego Maradona",
    service: "Interior design",
  },
  {
    id: 3,
    images: [
      {
        src: "/images/projects/guards-polo/cover.jpg",
        alt: "Guards Polo outside view render",
        width: 2000,
        height: 2000,
      },
      {
        src: "/images/projects/guards-polo/1.jpg",
        alt: "Guards Polo front view render",
        width: 2000,
        height: 2000,
      },
      {
        src: "/images/projects/guards-polo/2.jpg",
        alt: "Guards Polo side view render",
        width: 2000,
        height: 2000,
      },
      {
        src: "/images/projects/guards-polo/3.jpg",
        alt: "Guards Polo front view",
        width: 2000,
        height: 2000,
      },
      {
        src: "/images/projects/guards-polo/4.jpg",
        alt: "Guards Polo lounge",
        width: 2000,
        height: 2000,
      },
      {
        src: "/images/projects/guards-polo/5.jpg",
        alt: "Guards Polo lounge",
        width: 2000,
        height: 2000,
      },
      {
        src: "/images/projects/guards-polo/6.jpg",
        alt: "Guards Polo bedroom",
        width: 2000,
        height: 2000,
      },
      {
        src: "/images/projects/guards-polo/7.jpg",
        alt: "Guards Polo stairwell",
        width: 2000,
        height: 2000,
      },
      {
        src: "/images/projects/guards-polo/8.jpg",
        alt: "Guards Polo stairwell",
        width: 2000,
        height: 2000,
      },
    ],
    title: "Guards Polo",
    location: "Abuja",
    period: "2023",
    status: "Finished",
    client: "Guards Polo Club",
    service: "Full design",
  },
  {
    id: 4,
    images: [
      {
        src: "/images/projects/naf-residence/cover.jpg",
        alt: "NAF Residence front view render",
        width: 2000,
        height: 2000,
      },
      {
        src: "/images/projects/naf-residence/1.jpg",
        alt: "NAF Residence front view render",
        width: 2000,
        height: 2000,
      },
      {
        src: "/images/projects/naf-residence/2.jpg",
        alt: "NAF Residence front view render",
        width: 2000,
        height: 2000,
      },
      {
        src: "/images/projects/naf-residence/3.jpg",
        alt: "NAF Residence front view render",
        width: 2000,
        height: 2000,
      },
      {
        src: "/images/projects/naf-residence/4.jpg",
        alt: "NAF Residence front view render",
        width: 2000,
        height: 2000,
      },
      {
        src: "/images/projects/naf-residence/5.jpg",
        alt: "NAF Residence compound front view render",
        width: 2000,
        height: 2000,
      },
      {
        src: "/images/projects/naf-residence/6.jpg",
        alt: "NAF Residence compound front view render",
        width: 2000,
        height: 2000,
      },
      {
        src: "/images/projects/naf-residence/7.jpg",
        alt: "NAF Residence compound front view render",
        width: 2000,
        height: 2000,
      },
      {
        src: "/images/projects/naf-residence/8.jpg",
        alt: "NAF Residence master bedroom",
        width: 2000,
        height: 2000,
      },
      {
        src: "/images/projects/naf-residence/9.jpg",
        alt: "NAF Residence master bedroom",
        width: 2000,
        height: 2000,
      },
      {
        src: "/images/projects/naf-residence/10.jpg",
        alt: "NAF Residence master bedroom",
        width: 2000,
        height: 2000,
      },
      {
        src: "/images/projects/naf-residence/11.jpg",
        alt: "NAF Residence master bedroom",
        width: 2000,
        height: 2000,
      },
      {
        src: "/images/projects/naf-residence/12.jpg",
        alt: "NAF Residence master bedroom",
        width: 2000,
        height: 2000,
      },
      {
        src: "/images/projects/naf-residence/13.jpg",
        alt: "NAF Residence master bedroom",
        width: 2000,
        height: 2000,
      },
      {
        src: "/images/projects/naf-residence/14.jpg",
        alt: "NAF Residence master bedroom",
        width: 2000,
        height: 2000,
      },
      {
        src: "/images/projects/naf-residence/15.jpg",
        alt: "NAF Residence master bedroom balcony",
        width: 2000,
        height: 2000,
      },
      {
        src: "/images/projects/naf-residence/16.jpg",
        alt: "NAF Residence master bedroom",
        width: 2000,
        height: 2000,
      },
      {
        src: "/images/projects/naf-residence/17.jpg",
        alt: "NAF Residence bathroom",
        width: 2000,
        height: 2000,
      },
      {
        src: "/images/projects/naf-residence/18.jpg",
        alt: "NAF Residence bathroom",
        width: 2000,
        height: 2000,
      },
      {
        src: "/images/projects/naf-residence/19.jpg",
        alt: "NAF Residence bathroom",
        width: 2000,
        height: 2000,
      },
      {
        src: "/images/projects/naf-residence/20.jpg",
        alt: "NAF Residence bathroom",
        width: 2000,
        height: 2000,
      },
      {
        src: "/images/projects/naf-residence/21.jpg",
        alt: "NAF Residence bathroom",
        width: 2000,
        height: 2000,
      },
      {
        src: "/images/projects/naf-residence/22.jpg",
        alt: "NAF Residence bathroom",
        width: 2000,
        height: 2000,
      },
      {
        src: "/images/projects/naf-residence/23.jpg",
        alt: "NAF Residence bathroom",
        width: 2000,
        height: 2000,
      },
      {
        src: "/images/projects/naf-residence/24.jpg",
        alt: "NAF Residence bathroom",
        width: 2000,
        height: 2000,
      },
    ],
    title: "NAF Residence",
    location: "Kaduna",
    period: "2023",
    status: "Finished",
    client: "Nigerian Air Force",
    service: "Full design and project supervision",
  },
  {
    id: 5,
    images: [
      {
        src: "/images/projects/asokoro-residence/cover.jpg",
        alt: "Asokoro Residence living room",
        width: 2000,
        height: 2000,
      },
      {
        src: "/images/projects/asokoro-residence/1.jpg",
        alt: "Asokoro Residence living room",
        width: 2000,
        height: 2000,
      },
      {
        src: "/images/projects/asokoro-residence/2.jpg",
        alt: "Asokoro Residence living room",
        width: 2000,
        height: 2000,
      },
      {
        src: "/images/projects/asokoro-residence/3.jpg",
        alt: "Asokoro Residence living room",
        width: 2000,
        height: 2000,
      },
      {
        src: "/images/projects/asokoro-residence/4.jpg",
        alt: "Asokoro Residence bedroom",
        width: 2000,
        height: 2000,
      },
      {
        src: "/images/projects/asokoro-residence/5.jpg",
        alt: "Asokoro Residence bedroom",
        width: 2000,
        height: 2000,
      },
      {
        src: "/images/projects/asokoro-residence/6.jpg",
        alt: "Asokoro Residence bedroom",
        width: 2000,
        height: 2000,
      },
      {
        src: "/images/projects/asokoro-residence/7.jpg",
        alt: "Asokoro Residence bedroom",
        width: 2000,
        height: 2000,
      },
      {
        src: "/images/projects/asokoro-residence/8.jpg",
        alt: "Asokoro Residence bedroom",
        width: 2000,
        height: 2000,
      },
      {
        src: "/images/projects/asokoro-residence/9.jpg",
        alt: "Asokoro Residence bedroom closet",
        width: 2000,
        height: 2000,
      },
      {
        src: "/images/projects/asokoro-residence/10.jpg",
        alt: "Asokoro Residence office shelf",
        width: 2000,
        height: 2000,
      },
      {
        src: "/images/projects/asokoro-residence/11.jpg",
        alt: "Asokoro Residence kitchen",
        width: 2000,
        height: 2000,
      },
      {
        src: "/images/projects/asokoro-residence/12.jpg",
        alt: "Asokoro Residence kitchen",
        width: 2000,
        height: 2000,
      },
      {
        src: "/images/projects/asokoro-residence/13.jpg",
        alt: "Asokoro Residence kitchen",
        width: 2000,
        height: 2000,
      },
      {
        src: "/images/projects/asokoro-residence/14.jpg",
        alt: "Asokoro Residence kitchen",
        width: 2000,
        height: 2000,
      },
      {
        src: "/images/projects/asokoro-residence/15.jpg",
        alt: "Asokoro Residence kitchen",
        width: 2000,
        height: 2000,
      },
      {
        src: "/images/projects/asokoro-residence/16.jpg",
        alt: "Asokoro Residence kitchen",
        width: 2000,
        height: 2000,
      },
      {
        src: "/images/projects/asokoro-residence/17.jpg",
        alt: "Asokoro Residence kitchen",
        width: 2000,
        height: 2000,
      },
      {
        src: "/images/projects/asokoro-residence/18.jpg",
        alt: "Asokoro Residence office",
        width: 2000,
        height: 2000,
      },
      {
        src: "/images/projects/asokoro-residence/19.jpg",
        alt: "Asokoro Residence office",
        width: 2000,
        height: 2000,
      },
      {
        src: "/images/projects/asokoro-residence/20.jpg",
        alt: "Asokoro Residence office",
        width: 2000,
        height: 2000,
      },
      {
        src: "/images/projects/asokoro-residence/21.jpg",
        alt: "Asokoro Residence office",
        width: 2000,
        height: 2000,
      },
      {
        src: "/images/projects/asokoro-residence/22.jpg",
        alt: "Asokoro Residence office",
        width: 2000,
        height: 2000,
      },
      {
        src: "/images/projects/asokoro-residence/23.jpg",
        alt: "Asokoro Residence office",
        width: 2000,
        height: 2000,
      },
    ],
    title: "Asokoro Residence",
    location: "Abuja",
    period: "2023",
    status: "Finished",
    client: "Amin Goni",
    service: "Full design and project supervision",
  },
  {
    id: 6,
    images: [
      {
        src: "/images/projects/dokaji-residence/cover.jpg",
        alt: "Dokaji Residence compound front view render",
        width: 2000,
        height: 2000,
      },
      {
        src: "/images/projects/dokaji-residence/1.jpg",
        alt: "Dokaji Residence car park render",
        width: 2000,
        height: 2000,
      },
      {
        src: "/images/projects/dokaji-residence/2.jpg",
        alt: "Dokaji Residence side view render",
        width: 2000,
        height: 2000,
      },
      {
        src: "/images/projects/dokaji-residence/3.jpg",
        alt: "Dokaji Residence far side view render",
        width: 2000,
        height: 2000,
      },
      {
        src: "/images/projects/dokaji-residence/4.jpg",
        alt: "Dokaji Residence near front view render",
        width: 2000,
        height: 2000,
      },
      {
        src: "/images/projects/dokaji-residence/5.jpg",
        alt: "Dokaji Residence near front view render",
        width: 2000,
        height: 2000,
      },
    ],
    title: "Dokaji Residence",
    location: "Bauchi",
    period: "2023",
    status: "Finished",
    client: "Halliru Jika",
    service: "Full design and project supervision",
  },
  {
    id: 7,
    images: [
      {
        src: "/images/projects/imamu-duplex/cover.jpg",
        alt: "Imamu Duplex front view render",
        width: 2000,
        height: 2000,
      },
      {
        src: "/images/projects/imamu-duplex/1.jpg",
        alt: "Imamu Duplex front view render",
        width: 2000,
        height: 2000,
      },
      {
        src: "/images/projects/imamu-duplex/2.jpg",
        alt: "Imamu Duplex front view render",
        width: 2000,
        height: 2000,
      },
      {
        src: "/images/projects/imamu-duplex/3.jpg",
        alt: "Imamu Duplex front view render",
        width: 2000,
        height: 2000,
      },
      {
        src: "/images/projects/imamu-duplex/4.jpg",
        alt: "Imamu Duplex front view render",
        width: 2000,
        height: 2000,
      },
      {
        src: "/images/projects/imamu-duplex/5.jpg",
        alt: "Imamu Duplex front view render",
        width: 2000,
        height: 2000,
      },
    ],
    title: "Imamu Duplex",
    location: "Bauchi",
    period: "2023",
    status: "Finished",
    client: "Imamu",
    service: "Full design and project supervision",
  },
  {
    id: 8,
    images: [
      {
        src: "/images/projects/paradise-estates/cover.jpg",
        alt: "Paradise Estates living room",
        width: 2000,
        height: 2000,
      },
      {
        src: "/images/projects/paradise-estates/1.jpg",
        alt: "Paradise Estates family room",
        width: 2000,
        height: 2000,
      },
      {
        src: "/images/projects/paradise-estates/2.jpg",
        alt: "Paradise Estates stairwell",
        width: 2000,
        height: 2000,
      },
      {
        src: "/images/projects/paradise-estates/3.jpg",
        alt: "Paradise Estates stairwell",
        width: 2000,
        height: 2000,
      },
      {
        src: "/images/projects/paradise-estates/4.jpg",
        alt: "Paradise Estates dining table",
        width: 2000,
        height: 2000,
      },
    ],
    title: "Paradise Estates",
    location: "Abuja",
    period: "2023",
    status: "Finished",
    client: "Paradise Realty",
    service: "Full design and project supervision",
  },
  {
    id: 9,
    images: [
      {
        src: "/images/projects/naf-valley/cover.jpg",
        alt: "NAF Valley apartments front view render",
        width: 2000,
        height: 2000,
      },
      {
        src: "/images/projects/naf-valley/1.jpg",
        alt: "NAF Valley apartments front view render",
        width: 2000,
        height: 2000,
      },
      {
        src: "/images/projects/naf-valley/2.jpg",
        alt: "NAF Valley apartments front view render",
        width: 2000,
        height: 2000,
      },
      {
        src: "/images/projects/naf-valley/3.jpg",
        alt: "NAF Valley apartments front view render",
        width: 2000,
        height: 2000,
      },
      {
        src: "/images/projects/naf-valley/4.jpg",
        alt: "NAF Valley apartments front view render",
        width: 2000,
        height: 2000,
      },
      {
        src: "/images/projects/naf-valley/5.jpg",
        alt: "NAF Valley apartments driveway view render",
        width: 2000,
        height: 2000,
      },
      {
        src: "/images/projects/naf-valley/6.jpg",
        alt: "NAF Valley apartments front view render",
        width: 2000,
        height: 2000,
      },
    ],
    title: "NAF Valley Apartments",
    location: "Abuja",
    period: "2023",
    status: "Finished",
    client: "Nigerian Air Force",
    service: "Full design and project supervision",
  },
  {
    id: 10,
    images: [
      {
        src: "/images/projects/jahi-terraces/cover.jpg",
        alt: "Jahi Terraces front view render",
        width: 2000,
        height: 2000,
      },
      {
        src: "/images/projects/jahi-terraces/1.jpg",
        alt: "Jahi Terraces front view render night",
        width: 2000,
        height: 2000,
      },
      {
        src: "/images/projects/jahi-terraces/2.jpg",
        alt: "Jahi Terraces front view render",
        width: 2000,
        height: 2000,
      },
      {
        src: "/images/projects/jahi-terraces/3.jpg",
        alt: "Jahi Terraces front view render",
        width: 2000,
        height: 2000,
      },
      {
        src: "/images/projects/jahi-terraces/4.jpg",
        alt: "Jahi Terraces front view render",
        width: 2000,
        height: 2000,
      },
      {
        src: "/images/projects/jahi-terraces/5.jpg",
        alt: "Jahi Terraces front view render",
        width: 2000,
        height: 2000,
      },
      {
        src: "/images/projects/jahi-terraces/6.jpg",
        alt: "Jahi Terraces front view render",
        width: 2000,
        height: 2000,
      },
      {
        src: "/images/projects/jahi-terraces/7.jpg",
        alt: "Jahi Terraces front view render",
        width: 2000,
        height: 2000,
      },
      {
        src: "/images/projects/jahi-terraces/8.jpg",
        alt: "Jahi Terraces front view render",
        width: 2000,
        height: 2000,
      },
      {
        src: "/images/projects/jahi-terraces/9.jpg",
        alt: "Jahi Terraces front view render night",
        width: 2000,
        height: 2000,
      },
      {
        src: "/images/projects/jahi-terraces/10.jpg",
        alt: "Jahi Terraces front view render night",
        width: 2000,
        height: 2000,
      },
    ],
    title: "Jahi Terraces",
    location: "Abuja",
    period: "2023",
    status: "Finished",
    client: "MTN Nigeria",
    service: "Outside View Renders",
  },
  {
    id: 11,
    images: [
      {
        src: "/images/projects/grey-house/cover.jpg",
        alt: "Grey House front view render",
        width: 2000,
        height: 2000,
      },
      {
        src: "/images/projects/grey-house/1.jpg",
        alt: "Grey House isometric view render ",
        width: 2000,
        height: 2000,
      },
      {
        src: "/images/projects/grey-house/2.jpg",
        alt: "Grey House near isometric view render",
        width: 2000,
        height: 2000,
      },
      {
        src: "/images/projects/grey-house/3.jpg",
        alt: "Grey House near front view render",
        width: 2000,
        height: 2000,
      },
      {
        src: "/images/projects/grey-house/4.jpg",
        alt: "Grey House near front view sketch",
        width: 2000,
        height: 2000,
      },
      {
        src: "/images/projects/grey-house/5.jpg",
        alt: "Grey House near isometric view sketch",
        width: 2000,
        height: 2000,
      },
      {
        src: "/images/projects/grey-house/6.jpg",
        alt: "Grey House side view render",
        width: 2000,
        height: 2000,
      },
      {
        src: "/images/projects/grey-house/7.jpg",
        alt: "Grey House closet render",
        width: 2000,
        height: 2000,
      },
      {
        src: "/images/projects/grey-house/8.jpg",
        alt: "Grey House dining room render",
        width: 2000,
        height: 2000,
      },
      {
        src: "/images/projects/grey-house/9.jpg",
        alt: "Grey House living room render night",
        width: 2000,
        height: 2000,
      },
    ],
    title: "Grey House",
    location: "Bauchi",
    period: "2023",
    status: "Finished",
    client: "Ibrahim Ahmad",
    service: "Full design and project supervision",
  },
];
